
jobs:
- job: test
  strategy:
    matrix:
      Linuxpy35:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.5'
        TOX_CMD: 'py35'
      OSX py35:
        IMAGE_NAME: 'macos-10.13'
        PYTHON_VERSION: '3.5'
        TOX_CMD: 'py35'
      Windowspy35:
        IMAGE_NAME: 'vs2017-win2016'
        PYTHON_VERSION: '3.5'
        TOX_CMD: 'py35'
      Linuxpy36:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.6'
        TOX_CMD: 'py36'
      OSX py36:
        IMAGE_NAME: 'macos-10.13'
        PYTHON_VERSION: '3.6'
        TOX_CMD: 'py36'
      Windowspy36:
        IMAGE_NAME: 'vs2017-win2016'
        PYTHON_VERSION: '3.6'
        TOX_CMD: 'py36'
      Linuxpy37:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      OSX py37:
        IMAGE_NAME: 'macos-10.13'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      Windowspy37:
        IMAGE_NAME: 'vs2017-win2016'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      Linuxtensorflow_112:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.6'
        TOX_CMD: 'tensorflow_112'
      Linuxtensorflow_113:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.6'
        TOX_CMD: 'tensorflow_113'
      Linuxtensorflow-114:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'tensorflow-114'
      Linuxtensorflow_2:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'tensorflow_2'
      Linuxsetup:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'setup'
      Linuxflake8:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'flake8'
      Linuxcoverage:
        IMAGE_NAME: 'ubuntu-16.04'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'coverage'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - bash: pip install tox
    - bash: tox -e $TOX_CMD
