

jobs:
- job: py35
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
    - script: pip install tox
    - script: tox -e py35
- job: py36
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e py36
