

jobs:
- job: py35
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
    - script: pip install tox
    - script: tox -e py35
- job: py36
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e py36
- job: py37
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - script: pip install tox
    - script: tox -e py37
- job: tensorflow_112
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e tensorflow-112
- job: tensorflow_113
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e tensorflow-113
- job: tensorflow_114
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e tensorflow-114
- job: tensorflow_2
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - script: pip install tox
    - script: tox -e tensorflow-2
